apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kiln-v2.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kiln-v2.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kiln-v2.fullname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kiln-v2.fullname" . }}
    spec:
      containers:
        - name: {{ include "kiln-v2.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: kiln-secrets
      restartPolicy: Always
  strategy:
    type: Recreate